baseURL = "https://skyyds.cc/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "Test网站"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

summaryLength = 70

googleAnalytics = "312465587"

[params]
  # FixIt 主题版本
  version = "0.2.X"
  # 网站描述
  description = "这是我的全新 Hugo 网站"
  # 网站关键词
  keywords = ["Theme", "Hugo"]
  # 网站默认主题样式 ("light", "dark", "auto")
  defaultTheme = "auto"
  # FixIt 新增 | 0.2.12 开启 PWA 支持
  enablePWA = true

# FixIt 新增 | 0.2.0 应用图标配置
[params.app]
  # 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
  title = "FixIt"
  # 是否隐藏网站图标资源链接
  noFavicon = false
  # 更现代的 SVG 网站图标，可替代旧的 .png 和 .ico 文件
  svgFavicon = ""
  # Safari 图标颜色
  iconColor = "#5bbad5"
  # Windows v8-10 磁贴颜色
  tileColor = "#da532c"
  # FixIt 更改 | 0.2.12 Android 浏览器主题色
  [params.app.themeColor]
    light = "#ffffff"
    dark = "#252627"

# FixIt 新增 | 0.2.0 搜索配置
[params.search]
  enable = true
  # 搜索引擎的类型 ("lunr", "algolia")
  type = "algolia"
  # 文章内容最长索引长度
  contentLength = 4000
  # 搜索框的占位提示语
  placeholder = ""
  # FixIt 新增 | 0.2.1 最大结果数目
  maxResultLength = 10
  # FixIt 新增 | 0.2.3 结果内容片段长度
  snippetLength = 50
  # FixIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # FixIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [params.search.algolia]
    index = "new-index-1650706537"
    appID = "EBXP4IS3VN"
    searchKey = "44358d4860a665b56fd1ef41baf14671"

[outputs]
  home = ["HTML", "RSS", "JSON"]

# 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ("sticky", "normal", "auto")
    desktopMode = "sticky"
    # 移动端导航栏模式 ("sticky", "normal", "auto")
    mobileMode = "auto"
    # FixIt 新增 | 0.2.0 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = ""
      # 标题名称
      name = "Test site"
      # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
      pre = ""
      # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
      post = ""
      # FixIt 新增 | 0.2.5 是否为标题显示打字机动画
      typeit = false
    # FixIt 新增 | 0.2.12 页面头部导航栏副标题配置
    [params.header.subtitle]
      # 副标题名称
      name = ""
      # 是否为副标题显示打字机动画
      typeit = false

# 页面底部信息配置
  [params.footer]
    enable = true
    # FixIt 新增 | 0.2.0 自定义内容（支持 HTML 格式）
    custom = ''
    # FixIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
    hugo = false
    # FixIt 新增 | 0.2.0 是否显示版权信息
    copyright = true
    # FixIt 新增 | 0.2.0 是否显示作者
    author = true
    # 网站创立年份
    since = 2021
    # FixIt 新增 | 0.2.12 公网安备信息，仅在中国使用（支持 HTML 格式）
    gov = ""
    # FixIt 更改 | 0.2.12 ICP 备案信息，仅在中国使用（支持 HTML 格式）
    icp = ""
    # 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'


# 主页配置
[params.home]
  # FixIt 新增 | 0.2.0 RSS 文章数目
  rss = 10
  # 主页个人信息
  [params.home.profile]
    enable = true
    # FixIt 新增 | 0.2.13 选择使用 Gravatar 源站或其他镜像站，若留空则为默认的 "www.gravatar.com"
    gravatarSite = ""
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # 主页显示头像的 URL
    avatarURL = "/images/avatar.png"
    # FixIt 更改 | 0.2.7 主页显示的网站标题（支持 HTML 格式）
    title = ""
    # 主页显示的网站副标题
    subtitle = "这是我的全新 Hugo 网站"
    # 是否为副标题显示打字机动画
    typeit = true
    # 是否显示社交账号
    social = true
    # FixIt 新增 | 0.2.0 免责声明（支持 HTML 格式）
    disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6

# 作者的社交信息设置
  [params.social]
    GitHub = "xxxx"
    Twitter = "xxxx"
    Telegram = "xxxx"
    Bilibili = "xxx"
    Email = "xxxx@xxxx.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
    pre = ""
    # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时，将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "关于"
    url = "/about"
    title = ""
    weight = 4
# FixIt 更改 | 0.2.13 评论系统设置
[params.page.comment]
  enable = true
# Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
  [params.page.comment.gitalk]
    # FixIt 新增 | 0.1.1
    enable = true
    owner = "PeterBrave"
    repo = "gittalk"
    clientId = "521afdc7ac104cc06bc2"
    clientSecret = "cea057b7cbfbf3fe16308b36fd2a8f926a8a9d2a"

# FixIt 新增 | 0.2.0 网站分析配置
  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-J8B2RCKZT5"
      # 是否匿名化用户 IP
      anonymizeIP = true

# Busuanzi count since v0.2.12
# 不蒜子统计 since v0.2.12
[params.ibruce]
  enable = true
  # Enable in post meta
  # 在文章中开启
  enablePost = true
  # Site creation time
  # 网站创立时间
  siteTime = '2022-04-23T16:15:22+08:00'

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/Lruihao/FixIt/issues/43)
    noClasses = false

# 作者配置
[author]
  name = "skyyds"
  email = ""
  link = ""
